Rosalie241/RMG

Source/RMG/UserInterface/Widget/RomBrowserWidget.cpp, Source/RMG/UserInterface/Widget/RomBrowserWidget.hpp
If no ROM is selected, the Actions that refer to a selected ROM are disabled now. This also fixes a Crash when Play Game is clicked without a ROM selected.
=> Disable Actions in RomBrowser ContextMenu when not needed

Source/RMG/UserInterface/Widget/KeyBindButton.cpp, Source/RMG/UserInterface/Widget/KeyBindButton.hpp
Currently the User get no Feedback when editing a Hotkey, that he is currently editing which is confusing. This PR fixes this behaviour.
=> Give User Feedback when editing Hotkey

Package/com.github.Rosalie241.RMG.appdata.xml, Package/com.github.Rosalie241.RMG.desktop
This PR just add 2 categories. The Emulator category (subcategory of Game) is needed to make RMG appear in the Emulator section of the Software centers. The Qt category just shows, that this Program uses a Qt GUI.
=> Add 2 categories

Package/com.github.Rosalie241.RMG.desktop
This just tells the File managers, that RMG can open Nintendo 64 ROM files, so RMG will appear direct in the open with list of Nintendo 64 ROM files by default.
=> Add MimeType to .desktop

Source/RMG-Audio/main.cpp, Source/RMG-Core/Core.cpp, Source/RMG-Core/Directories.cpp, Source/RMG-Core/Key.cpp, Source/RMG-Core/MediaLoader.cpp, Source/RMG-Core/Plugins.cpp, Source/RMG-Core/Rom.cpp, Source/RMG-Core/RomHeader.hpp, Source/RMG-Core/RomSettings.hpp, Source/RMG-Core/Screenshot.cpp, Source/RMG-Core/Settings/Settings.cpp, Source/RMG-Core/SpeedLimiter.cpp, Source/RMG-Core/VidExt.cpp, Source/RMG-Core/Video.cpp, Source/RMG/Callbacks.hpp, Source/RMG/UserInterface/Dialog/SettingsDialog.hpp, Source/RMG/UserInterface/Widget/OGLWidget.cpp, Source/RMG/UserInterface/Widget/RomBrowserWidget.cpp
This should prevent any issues like #42 occurring again due to changes in STL implementations or refactors of RMG.
* `<cstdlib>` for `malloc()`, `free()`
* `<cstdint>` for `uint8_t`
* `<string>` for `std::string`
* `<cstdlib>` for `std::getenv()`
* `<string>` for `std::string`
* `<cstdint>` for `uint8_t`
* redundant `<string>` as it is included in the associated header
* `<cstdlib>` for `malloc()`, `free()`
* remove unused `<iostream>`
* change `<cinttypes>` to `<cstdint>` because extras aren't used
* change `<cinttypes>` to `<cstdint>` because extras aren't used
* `<string>` for `std::string`
* remove unused `<exception>`
* remove redundant `<string>` as it is included in the associated header
* `<string>` for `std::string`
* `<string>` for `std::string`
* `<string>` for `std::string`
* …
=> Add missing STL includes and remove redundant and unused ones

Source/RMG-Core/Settings/Settings.cpp, Source/RMG/UserInterface/Dialog/SettingsDialog.cpp
SettingsDialog: Extend IPL ROM extensions
IPL ROMs use the same extensions as basic N64 ROMs.
SettingsDialog: Fix default saveDiskFormat
Clicking the button to `Restore Defaults` results in the wrong value for the `saveDiskFormat`. Default is `RAM Area Only` (1).
=> SettingsDialog: Minor fixes

Source/3rdParty/CMakeLists.txt
Keep the binary name consistent and let it choose the instruction set (SSE2 or no SSE) automatically.
=> 3rdParty: Remove postfix for cxd4 RSP

Source/RMG-Input/CMakeLists.txt, Source/RMG-Input/UserInterface/Widget/ControllerImageWidget.cpp, Source/RMG-Input/UserInterface/Widget/ControllerWidget.cpp, Source/RMG-Input/common.cpp, Source/RMG-Input/common.hpp, Source/RMG-Input/main.cpp
The implementation takes configured deadzone and range into account, with 9% deadzone equating to the real N64 deadzone.
Implementation based on [fzurita's in mupen64plus-ae](https://github.com/mupen64plus-ae/mupen64plus-ae/blob/cea9d99c3c7f908cfdb3d81f254854c47981b7b6/mupen64plus-input-android/src/plugin.cpp#L322-L369), which in turn is based on [MerryMage's, with deadzone by kev4cards in ares](https://github.com/ares-emulator/ares/blob/master/ares/n64/controller/gamepad/gamepad.cpp#L192-L229).
=> RMG-Input: implement octagonal input range

Source/RMG/UserInterface/Widget/RomBrowserWidget.cpp
- Fixed a bug which can cause the ROM browser to crash if RMG is closed while the ROM browser is loading.
- Removed the need to temporarily save and then restore the config file's "Columns" setting when updating the column sizes in "on_RomBrowserThread_Finished".
- Rearranged some code in "on_RomBrowserThread_Finished" to make the above change work.
=> Fix ROM Browser Crash

Source/RMG-Core/CachedRomHeaderAndSettings.cpp, Source/RMG-Core/RomHeader.cpp, Source/RMG-Core/RomHeader.hpp, Source/RMG-Core/Settings/Settings.cpp, Source/RMG/UserInterface/Dialog/RomInfoDialog.cpp, Source/RMG/UserInterface/Dialog/RomInfoDialog.ui, Source/RMG/UserInterface/Widget/RomBrowserWidget.cpp, Source/RMG/UserInterface/Widget/RomBrowserWidget.hpp
First there were [moveable columns...](https://github.com/Rosalie241/RMG/pull/105)
Next came the ability to [toggle columns on and off...](https://github.com/Rosalie241/RMG/pull/111)
And now, at long last, I'm proud to present the third and final phase of my grand plan to overhaul the ROM browser's "Game List" mode: **Additional Columns**. This is what it's all been leading up to!
This pull request implements the following changes:
- Six new columns (all of which are hidden by default) have been added to "Game List" mode in the ROM browser:
- Game Format: Displays whether the ROM file is a disk or cartridge game. Listed as "Format" on the header to save space. Generated in "RMG-Core/Rom.cpp".
- File Name: Displays the name of the ROM file, minus its file extension. Generated internally by …
=> "Game List" Mode Overhaul: Phase 3

Source/RMG-Core/Settings/Settings.cpp, Source/RMG-Core/Settings/SettingsID.hpp, Source/RMG-Input/UserInterface/Widget/ControllerImageWidget.cpp, Source/RMG-Input/UserInterface/Widget/ControllerImageWidget.hpp, Source/RMG-Input/UserInterface/Widget/ControllerWidget.cpp, Source/RMG-Input/UserInterface/Widget/ControllerWidget.hpp, Source/RMG-Input/UserInterface/Widget/ControllerWidget.ui, Source/RMG-Input/main.cpp
Allow users to set a sensitivity for analog stick input. The range is from 25% to 175% of the actual input. Lower than 100% sensitivity will result in not being able to reach maximum emulated N64 input; i.e. lower than 85 absolute value along the axes. Greater than 100% sensitivity causes the emulated input to reach its max sooner than. When emulated stick input is mapped to a digital input on the real input device, e.g. a keyboard, values under 100% will limit the maximum value similarly to analog mappings, while values above 100% will have no impact on the emulated input.
=> Introduce analog stick sensitivity

Source/RMG-Input/UserInterface/Widget/ControllerImageWidget.cpp, Source/RMG-Input/main.cpp
Move application of settings that are for the real input device outside of octagon simulation. This should make implementing the changes from #142 much simpler.
=> RMG-Input: refactor deadzone and sensitivity

Package/com.github.Rosalie241.RMG.desktop
Right now (in GNOME at least), when you type "RMG", this application doesn't come up.
Adding "RMG" as a Keyword in the desktop entry should allow a person to type "RMG" and GNOME search will find it and suggest it.
=> Add 'RMG' as a keyword to the desktop entry

Source/RMG-Input/main.cpp
This PR replaces PR #142. It addresses the comments from that PR as well as reworked to fit into the recent refactor. The code is designed to set a a value, maxInpuRadius, derived from the mapping equation to encompass the octagon of the N64. With the octagon fully encompassed by this circle, input can now abide by the mapping equation instead of having to be re-scaled as it is in the current code. Any input that exceeds the octagon is either clamped by the edge of the octagon or to maxAxis (which coincides with the cardinal vertices of the octagon). Lastly, an epsilon is added for each direction in the case that floating point error leaves a value just shy of next the whole number. Ceil or round would have been too aggressive when considering fine aiming just around the deadzone-input …
=> RMG-Input: improve control stick behavior

Source/3rdParty/CMakeLists.txt
Fixes: 768064a2e187282f0b29b9123ba3333c90470ddb
Apologies, I failed to commit properly yesterday and sent you the wrong patch...
=> cmake: fix the NO_ASM option

Source/RMG-Core/Settings/Settings.cpp
The trivial resampler produces rather poor audio quality. Linear is probably a more appropriate default for most users.
=> Change the default audio resampler from "trivial" to "src-linear"

Source/3rdParty/mupen64plus-input-gca/src/config.rs
As requested in #290. Adds `None` as a possible N64Button, essentially allowing buttons to be disabled.
=> 3rdParty: Allow disabling buttons for GC Adapter

Source/3rdParty/mupen64plus-input-raphnetraw/projects/unix/Makefile
Upstream-PR: https://github.com/raphnet/mupen64plus-input-raphnetraw/pull/17
Upstream hasn't been touched in 3 years and it has already pending unreviewed PRs so I thought it would be better to send it here too. I am unsure what your preferred way to merge non-upstreamed changes?
=> mupen64plus-input-raphnetraw: don't hard-code pkg-config

Source/3rdParty/mupen64plus-input-raphnetraw/projects/unix/Makefile
I don't think I quite did enough in the last PR so I changed it to better match the style in mupen64plus-core.
Upstream-PR: https://github.com/raphnet/mupen64plus-input-raphnetraw/pull/17
=> 3rdParty: improve the hidapi check in mupen64plus-input-raphnetraw

Source/RMG-Input/UserInterface/Widget/ControllerWidget.ui
Fix a typo, instead of being `left:` it should be `Left:` to match with the other instances of the same.
=> Update ControllerWidget.ui to fix a typo

Package/AppImage/Create.sh
This is actually not needed anymore and likely what caused #344 
See https://github.com/probonopd/PrusaSlicer.AppImage/pull/2 for more info, that user previously had issues with nvidia that were fixed by not patching rpath anymore. 
Originally the rpath patch was introduced as a method to overwrite a possible existing rpath like `/usr/lib` in the libraries that get bundled, this has priority over `--library-path` in the dynamic linker so it had to be done to avoid having the appimage try using libraries on the host. 
Now `lib4bin` will fix that if it detects that a lib comes with an absolute path rpath we don't have to patch all the libs which can break them, which means this flag is not needed anymore.
=> remove rpath patch, this is not needed
